### PR TITLE
Change older singularity/apptainer to auto-load 1.1

### PR DESCRIPTION
**Pull request by bartoldeman**
So most existing module scripts keep working.

### CODE REVIEW

**Comment by mboisson** [comment]
This will put multiple paths in the PATH, is that desirable ?

**Review by ccoulombe — APPROVED** [review]
lgtm

**Comment by mboisson** [comment]
Also, with the other PR, it will lead to a warning (`singularity` can't load `apptainer`, they are in the same family), won't it ?

**Comment by bartoldeman** [comment]
If I do it manually it works ok:
```
[oldeman@build-node ~]$ module load singularity/3.7
--------------------------------------------------------------------------------------------------------------------------------------------------------
There are messages associated with the following module(s):
--------------------------------------------------------------------------------------------------------------------------------------------------------

singularity/3.7:
This module is deprecated and will be removed in the future due to security reasons.
Please move to apptainer/1.1 or, if you use encrypted containers, apptainer-suid/1.1.
Ce module est marqué pour être retiré et sera supprimé dans le futur pour des raisons de sécurité.
Utilisez plutôt apptainer/1.1, ou si vous utilisez des conteneurs cryptés, apptainer-suid/1.1.

--------------------------------------------------------------------------------------------------------------------------------------------------------

[oldeman@build-node ~]$ module load apptainer/1.1

Lmod is automatically replacing "singularity/3.7" with "apptainer/1.1.8".
```
but if I put the `load("apptainer")` in the singularity module it goes in an infinite loop ???
```
[oldeman@build-node ~]$ module use git/software-stack-custom/modules

Due to MODULEPATH changes, the following have been reloaded:
  1) CCconfig     2) StdEnv/2020     3) gentoo/2020

[oldeman@build-node ~]$ module load singularity/3.7

Lmod is automatically replacing "apptainer/1.1.8" with "singularity/3.7".


Lmod is automatically replacing "apptainer/1.1.8" with "singularity/3.7".


Lmod is automatically replacing "apptainer/1.1.8" with "singularity/3.7".


```
```

**Comment by mboisson** [comment]
I think it may be best to use: 
```
module-alias singularity/3 apptainer/1.1
module-alias singularity/3.7 apptainer/1.1
module-alias singularity/3.8 apptainer/1.1
module-alias singularity/1.0 apptainer/1.1
``` 
in the `modulerc` files

**Review by mboisson — CHANGES_REQUESTED** [review]
This can't work with the family directive.

**Comment by bartoldeman** [comment]
It seems to work ok with apptainer/1.0, we could just remove singularity from the family then?

**Comment by mboisson** [comment]
LGTM now

**Review by mboisson — APPROVED** [review]

**Pull request merged**
