### PR TITLE
Added PIP_CONSTRAINT environment variable on build-node only

### PR DESCRIPTION
**Pull request by ccoulombe**
This goes hand in hand with https://github.com/ComputeCanada/software-stack-config/pull/62

### CODE REVIEW

**Comment by mboisson** [comment]
@bartoldeman, what do you think ? I think instead of "polluting" the Gentoo module with build-node-only stuff, we should set it in the /etc/profile.d scripts.

**Comment by bartoldeman** [comment]
yes this doesn't look like the right place. Can it be put in scripts? After all if you want to test things (manual pip) you want an environment similar to the clusters?

**Comment by mboisson** [comment]
Ah, indeed, we could simply define it in `build_wheels.sh` maybe, as this is the main use case.

**Comment by ccoulombe** [comment]
That was my first thought, but it needs to be in the environment as we often pre-build wheels manually before using the script, and it is also for modules.

**Comment by mboisson** [comment]
Then I think we can just put it in `/etc/profile.d/z-00-computecanada.sh` on our build nodes.

**Comment by ccoulombe** [comment]
`export PIP_CONSTRAINT=/cvmfs/soft.computecanada.ca/config/python/constraints-buildnode.txt` has been added locally on both build-nodes to `/etc/profile.d/z-00-computecanada.sh`

**Pull request closed without merging**
